name: Deploy React App to EC2

on:
  push:
    branches:
      - main
# branch changed
jobs:
  deploy:
    runs-on: ubuntu-latest
#code-start
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
# code-end
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
#code-upgrade
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/react-app && git pull && npm install && npm run build && sudo systemctl restart nginx"